ALTER TABLE `grr_utilisateurs` ADD `tel` VARCHAR( 100 ) NOT NULL ,
ADD `champs_libre` VARCHAR( 255 ) NOT NULL;

ALTER TABLE `grr_plugins_kzd_restauration`
ADD  `petitdej_heure1` varchar(100) DEFAULT NULL,
ADD  `petitdej_allegro_nb1` int(11) DEFAULT NULL,
ADD  `petitdej_parisien_nb1` int(11) DEFAULT NULL,
ADD `petitdej_club1` int(11) DEFAULT NULL,
ADD `petitdej_heure2` varchar(100) DEFAULT NULL,
ADD `petitdej_allegro_nb2` int(11) DEFAULT NULL,
ADD `petitdej_parisien_nb2` int(11) DEFAULT NULL,
ADD `petitdej_club2` int(11) DEFAULT NULL,
ADD `petitdej_heure3` varchar(100) DEFAULT NULL,
ADD `petitdej_allegro_nb3` int(11) DEFAULT NULL,
ADD`petitdej_parisien_nb3` int(11) DEFAULT NULL,
ADD`petitdej_club3` int(11) DEFAULT NULL,
ADD`petitdej_divers` text,
ADD `club_heure1` varchar(100) DEFAULT NULL,
ADD `club_classique1` int(11) DEFAULT NULL,
ADD `club_decouverte1` int(11) DEFAULT NULL,
ADD `club_terroir1` int(11) DEFAULT NULL,
ADD `club_vin_sodexo1` tinyint(1) DEFAULT NULL,
ADD `club_vin_organisme1` tinyint(1) DEFAULT NULL,
ADD `club_cafe1` int(11) DEFAULT NULL,
ADD `club_eau1` int(11) DEFAULT NULL,
ADD `club_heure2` varchar(100) DEFAULT NULL,
ADD `club_classique2` int(11) DEFAULT NULL,
ADD `club_decouverte2` int(11) DEFAULT NULL,
ADD  `club_terroir2` int(11) DEFAULT NULL,
ADD `club_vin_sodexo2` tinyint(1) DEFAULT NULL,
ADD  `club_vin_organisme2` tinyint(1) DEFAULT NULL,
ADD `club_cafe2` int(11) DEFAULT NULL,
ADD `club_eau2` int(11) DEFAULT NULL,
ADD `club_heure3` varchar(100) DEFAULT NULL,
ADD `club_classique3` int(11) DEFAULT NULL,
ADD `club_decouverte3` int(11) DEFAULT NULL,
ADD `club_terroir3` int(11) DEFAULT NULL,
ADD `club_vin_sodexo3` tinyint(1) DEFAULT NULL,
ADD `club_vin_organisme3` tinyint(1) DEFAULT NULL,
ADD `club_cafe3` int(11) DEFAULT NULL,
ADD `club_eau3` int(11) DEFAULT NULL;